<font size=4 face='楷体'>

## JS 异常处理

### 基于回调的异步方案

```javascript
const fs = require('fs');

fs.readFile('/tmp/hello', 'utf8', (err， data) => {
  if (err) {
    console.error(err);
  } else {
    console.log(data);
  }
});

```

### 基于 Promise 的异步方案

```javascript
fs.readFile('/tmp/hello', 'utf8')
  .then((data) => {
    console.log(data)
  })
  .catch((err) => {
    console.error(err)
  })
```

### 基于事件的全局异常捕获

node.js 例子

```javascript
process.on('uncaughtException', (err) => {
  console.error(err)
})

setTimeout(() => {
  throw new Error('fail')
}, 500)
```

### Reference

[javascript 中异步操作的异常怎么处理](https://www.zhihu.com/question/65612078/answer/232885496)

**2022.10.11**
